'use strict';(function(){function ka(a,b,c){return a.call.apply(a.bind,arguments)}function la(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return u.apply(null,arguments)}function ma(a,
b){this.a=a;this.o=b||a;this.c=this.o.document}function F(a,b,c,d){b=a.c.createElement(b);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?b.style.cssText=c[e]:b.setAttribute(e,c[e]));d&&b.appendChild(a.c.createTextNode(d));return b}function L(a,b,c){(a=a.c.getElementsByTagName(b)[0])||(a=document.documentElement);a.insertBefore(c,a.lastChild)}function y(a){a.parentNode&&a.parentNode.removeChild(a)}function w(a,b,c){b=b||[];c=c||[];for(var d=a.className.split(/\s+/),e=0;e<b.length;e+=1){for(var f=
!1,g=0;g<d.length;g+=1)if(b[e]===d[g]){f=!0;break}f||d.push(b[e])}b=[];for(e=0;e<d.length;e+=1){f=!1;for(g=0;g<c.length;g+=1)if(d[e]===c[g]){f=!0;break}f||b.push(d[e])}a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function M(a,b){a=a.className.split(/\s+/);for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return!0;return!1}function na(a){return a.o.location.hostname||a.a.location.hostname}function N(a,b,c){function d(){h&&e&&f&&(h(g),h=null)}b=F(a,"link",{rel:"stylesheet",href:b,media:"all"});
var e=!1,f=!0,g=null,h=c||null;oa?(b.onload=function(){e=!0;d()},b.onerror=function(){e=!0;g=Error("Stylesheet failed to load");d()}):setTimeout(function(){e=!0;d()},0);L(a,"head",b)}function G(a,b,c,d){var e=a.c.getElementsByTagName("head")[0];if(e){var f=F(a,"script",{src:b}),g=!1;f.onload=f.onreadystatechange=function(){g||this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState||(g=!0,c&&c(null),f.onload=f.onreadystatechange=null,"HEAD"==f.parentNode.tagName&&e.removeChild(f))};
e.appendChild(f);setTimeout(function(){g||(g=!0,c&&c(Error("Script load timeout")))},d||5E3);return f}return null}function O(){this.a=0;this.c=null}function P(a){a.a++;return function(){a.a--;Q(a)}}function R(a,b){a.c=b;Q(a)}function Q(a){0==a.a&&a.c&&(a.c(),a.c=null)}function S(a){this.a=a||"-"}function t(a,b){this.c=a;this.f=4;this.a="n";(a=(b||"n4").match(/^([nio])([1-9])$/i))&&(this.a=a[1],this.f=parseInt(a[2],10))}function pa(a){return T(a)+" "+(a.f+"00 300px ")+U(a.c)}function U(a){var b=[];
a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");-1!=d.indexOf(" ")||/^\d/.test(d)?b.push("'"+d+"'"):b.push(d)}return b.join(",")}function r(a){return a.a+a.f}function T(a){var b="normal";"o"===a.a?b="oblique":"i"===a.a&&(b="italic");return b}function qa(a,b){this.c=a;this.f=a.o.document.documentElement;this.h=b;this.a=new S("-");this.j=!1!==b.events;this.g=!1!==b.classes}function ra(a){a.g&&w(a.f,[a.a.c("wf","loading")]);x(a,"loading")}function V(a){if(a.g){var b=M(a.f,
a.a.c("wf","active")),c=[],d=[a.a.c("wf","loading")];b||c.push(a.a.c("wf","inactive"));w(a.f,c,d)}x(a,"inactive")}function x(a,b,c){if(a.j&&a.h[b])if(c)a.h[b](c.c,r(c));else a.h[b]()}function sa(){this.c={}}function ta(a,b,c){var d=[],e;for(e in b)if(b.hasOwnProperty(e)){var f=a.c[e];f&&d.push(f(b[e],c))}return d}function z(a,b){this.c=a;this.f=b;this.a=F(this.c,"span",{"aria-hidden":"true"},this.f)}function A(a){L(a.c,"body",a.a)}function B(a){return"display:block;position:absolute;top:-9999px;left:-9999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+
U(a.c)+";font-style:"+(T(a)+";font-weight:"+(a.f+"00;"))}function W(a,b,c,d,e,f){this.g=a;this.j=b;this.a=d;this.c=c;this.f=e||3E3;this.h=f||void 0}function X(a,b,c,d,e,f,g){this.v=a;this.B=b;this.c=c;this.a=d;this.s=g||"BESbswy";this.f={};this.w=e||3E3;this.u=f||null;this.m=this.j=this.h=this.g=null;this.g=new z(this.c,this.s);this.h=new z(this.c,this.s);this.j=new z(this.c,this.s);this.m=new z(this.c,this.s);a=new t(this.a.c+",serif",r(this.a));a=B(a);this.g.a.style.cssText=a;a=new t(this.a.c+",sans-serif",
r(this.a));a=B(a);this.h.a.style.cssText=a;a=new t("serif",r(this.a));a=B(a);this.j.a.style.cssText=a;a=new t("sans-serif",r(this.a));a=B(a);this.m.a.style.cssText=a;A(this.g);A(this.h);A(this.j);A(this.m)}function Y(){if(null===H){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent);H=!!a&&(536>parseInt(a[1],10)||536===parseInt(a[1],10)&&11>=parseInt(a[2],10))}return H}function Z(a,b,c){for(var d in C)if(C.hasOwnProperty(d)&&b===a.f[C[d]]&&c===a.f[C[d]])return!0;return!1}
function aa(a){var b=a.g.a.offsetWidth,c=a.h.a.offsetWidth,d;(d=b===a.f.serif&&c===a.f["sans-serif"])||(d=Y()&&Z(a,b,c));d?D()-a.A>=a.w?Y()&&Z(a,b,c)&&(null===a.u||a.u.hasOwnProperty(a.a.c))?I(a,a.v):I(a,a.B):ua(a):I(a,a.v)}function ua(a){setTimeout(u(function(){aa(this)},a),50)}function I(a,b){setTimeout(u(function(){y(this.g.a);y(this.h.a);y(this.j.a);y(this.m.a);b(this.a)},a),0)}function J(a,b,c){this.c=a;this.a=b;this.f=0;this.m=this.j=!1;this.s=c}function ba(a){0==--a.f&&a.j&&(a.m?(a=a.a,a.g&&
w(a.f,[a.a.c("wf","active")],[a.a.c("wf","loading"),a.a.c("wf","inactive")]),x(a,"active")):V(a.a))}function ca(a){this.j=a;this.a=new sa;this.h=0;this.f=this.g=!0}function va(a,b,c,d,e){var f=0==--a.h;(a.f||a.g)&&setTimeout(function(){var g=e||null,h=d||{};if(0===c.length&&f)V(b.a);else{b.f+=c.length;f&&(b.j=f);var k,l=[];for(k=0;k<c.length;k++){var m=c[k],n=h[m.c],q=b.a,p=m;q.g&&w(q.f,[q.a.c("wf",p.c,r(p).toString(),"loading")]);x(q,"fontloading",p);q=null;if(null===E)if(window.FontFace){p=/Gecko.*Firefox\/(\d+)/.exec(window.navigator.userAgent);
var wa=/OS X.*Version\/10\..*Safari/.exec(window.navigator.userAgent)&&/Apple/.exec(window.navigator.vendor);E=p?42<parseInt(p[1],10):wa?!1:!0}else E=!1;E?q=new W(u(b.g,b),u(b.h,b),b.c,m,b.s,n):q=new X(u(b.g,b),u(b.h,b),b.c,m,b.s,g,n);l.push(q)}for(k=0;k<l.length;k++)l[k].start()}},0)}function xa(a,b,c){var d=[],e=c.timeout;ra(b);d=ta(a.a,c,a.c);var f=new J(a.c,b,e);a.h=d.length;b=0;for(c=d.length;b<c;b++)d[b].load(function(g,h,k){va(a,f,g,h,k)})}function da(a,b){this.c=a;this.a=b}function ea(a,b){this.c=
a;this.a=b}function ya(a,b){a?this.c=a:this.c=za;this.a=[];this.f=[];this.g=b||""}function Aa(a,b){for(var c=b.length,d=0;d<c;d++){var e=b[d].split(":");3==e.length&&a.f.push(e.pop());var f="";2==e.length&&""!=e[1]&&(f=":");a.a.push(e.join(f))}}function Ba(a){if(0==a.a.length)throw Error("No fonts to load!");if(-1!=a.c.indexOf("kit="))return a.c;for(var b=a.a.length,c=[],d=0;d<b;d++)c.push(a.a[d].replace(/ /g,"+"));b=a.c+"?family="+c.join("%7C");0<a.f.length&&(b+="&subset="+a.f.join(","));0<a.g.length&&
(b+="&text="+encodeURIComponent(a.g));return b}function Ca(a){this.f=a;this.a=[];this.c={}}function Da(a){for(var b=a.f.length,c=0;c<b;c++){var d=a.f[c].split(":"),e=d[0].replace(/\+/g," "),f=["n4"];if(2<=d.length){var g=d[1];var h=[];if(g){g=g.split(",");for(var k=g.length,l=0;l<k;l++){var m=g[l];if(m.match(/^[\w-]+$/)){var n=Ea.exec(m.toLowerCase());if(null==n)m="";else{m=n[2];m=null==m||""==m?"n":Fa[m];n=n[1];if(null==n||""==n)n="4";else{var q=Ga[n];n=q?q:isNaN(n)?"4":n.substr(0,1)}m=[m,n].join("")}}else m=
"";m&&h.push(m)}}0<h.length&&(f=h);3==d.length&&(d=d[2],h=[],d=d?d.split(","):h,0<d.length&&(d=fa[d[0]])&&(a.c[e]=d))}a.c[e]||(d=fa[e])&&(a.c[e]=d);for(d=0;d<f.length;d+=1)a.a.push(new t(e,f[d]))}}function ha(a,b){this.c=a;this.a=b}function ia(a,b){this.c=a;this.a=b}function ja(a,b){this.c=a;this.f=b;this.a=[]}var D=Date.now||function(){return+new Date},oa=!!window.FontFace;S.prototype.c=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.a)};
W.prototype.start=function(){var a=this.c.o.document,b=this,c=D(),d=new Promise(function(g,h){function k(){D()-c>=b.f?h():a.fonts.load(pa(b.a),b.h).then(function(l){1<=l.length?g():setTimeout(k,25)},function(){h()})}k()}),e=null,f=new Promise(function(g,h){e=setTimeout(h,b.f)});Promise.race([f,d]).then(function(){e&&(clearTimeout(e),e=null);b.g(b.a)},function(){b.j(b.a)})};var C={D:"serif",C:"sans-serif"},H=null;X.prototype.start=function(){this.f.serif=this.j.a.offsetWidth;this.f["sans-serif"]=this.m.a.offsetWidth;
this.A=D();aa(this)};var E=null;J.prototype.g=function(a){var b=this.a;b.g&&w(b.f,[b.a.c("wf",a.c,r(a).toString(),"active")],[b.a.c("wf",a.c,r(a).toString(),"loading"),b.a.c("wf",a.c,r(a).toString(),"inactive")]);x(b,"fontactive",a);this.m=!0;ba(this)};J.prototype.h=function(a){var b=this.a;if(b.g){var c=M(b.f,b.a.c("wf",a.c,r(a).toString(),"active")),d=[],e=[b.a.c("wf",a.c,r(a).toString(),"loading")];c||d.push(b.a.c("wf",a.c,r(a).toString(),"inactive"));w(b.f,d,e)}x(b,"fontinactive",a);ba(this)};
ca.prototype.load=function(a){this.c=new ma(this.j,a.context||this.j);this.g=!1!==a.events;this.f=!1!==a.classes;xa(this,new qa(this.c,a),a)};da.prototype.load=function(a){function b(){if(f["__mti_fntLst"+d]){var g=f["__mti_fntLst"+d](),h=[],k;if(g)for(var l=0;l<g.length;l++){var m=g[l].fontfamily;void 0!=g[l].fontStyle&&void 0!=g[l].fontWeight?(k=g[l].fontStyle+g[l].fontWeight,h.push(new t(m,k))):h.push(new t(m))}a(h)}else setTimeout(function(){b()},50)}var c=this,d=c.a.projectId,e=c.a.version;if(d){var f=
c.c.o;G(this.c,(c.a.api||"https://fast.fonts.net/jsapi")+"/"+d+".js"+(e?"?v="+e:""),function(g){g?a([]):(f["__MonotypeConfiguration__"+d]=function(){return c.a},b())}).id="__MonotypeAPIScript__"+d}else a([])};ea.prototype.load=function(a){var b,c=this.a.urls||[],d=this.a.families||[],e=this.a.testStrings||{},f=new O;var g=0;for(b=c.length;g<b;g++)N(this.c,c[g],P(f));var h=[];g=0;for(b=d.length;g<b;g++)if(c=d[g].split(":"),c[1])for(var k=c[1].split(","),l=0;l<k.length;l+=1)h.push(new t(c[0],k[l]));
else h.push(new t(c[0]));R(f,function(){a(h,e)})};var za="https://fonts.googleapis.com/css",fa={latin:"BESbswy","latin-ext":"\u00e7\u00f6\u00fc\u011f\u015f",cyrillic:"\u0439\u044f\u0416",greek:"\u03b1\u03b2\u03a3",khmer:"\u1780\u1781\u1782",Hanuman:"\u1780\u1781\u1782"},Ga={thin:"1",extralight:"2","extra-light":"2",ultralight:"2","ultra-light":"2",light:"3",regular:"4",book:"4",medium:"5","semi-bold":"6",semibold:"6","demi-bold":"6",demibold:"6",bold:"7","extra-bold":"8",extrabold:"8","ultra-bold":"8",
ultrabold:"8",black:"9",heavy:"9",l:"3",r:"4",b:"7"},Fa={i:"i",italic:"i",n:"n",normal:"n"},Ea=/^(thin|(?:(?:extra|ultra)-?)?light|regular|book|medium|(?:(?:semi|demi|extra|ultra)-?)?bold|black|heavy|l|r|b|[1-9]00)?(n|i|normal|italic)?$/,Ha={Arimo:!0,Cousine:!0,Tinos:!0};ha.prototype.load=function(a){var b=new O,c=this.c,d=new ya(this.a.api,this.a.text),e=this.a.families;Aa(d,e);var f=new Ca(e);Da(f);N(c,Ba(d),P(b));R(b,function(){a(f.a,f.c,Ha)})};ia.prototype.load=function(a){var b=this.a.id,c=this.c.o;
b?G(this.c,(this.a.api||"https://use.typekit.net")+"/"+b+".js",function(d){if(d)a([]);else if(c.Typekit&&c.Typekit.config&&c.Typekit.config.fn){d=c.Typekit.config.fn;for(var e=[],f=0;f<d.length;f+=2)for(var g=d[f],h=d[f+1],k=0;k<h.length;k++)e.push(new t(g,h[k]));try{c.Typekit.load({events:!1,classes:!1,async:!0})}catch(l){}a(e)}},2E3):a([])};ja.prototype.load=function(a){var b=this.f.id,c=this.c.o,d=this;b?(c.__webfontfontdeckmodule__||(c.__webfontfontdeckmodule__={}),c.__webfontfontdeckmodule__[b]=
function(e,f){e=0;for(var g=f.fonts.length;e<g;++e){var h=f.fonts[e],k=d.a,l=k.push,m=h.name;h="font-weight:"+h.weight+";font-style:"+h.style;var n=4,q="n",p=null;h&&((p=h.match(/(normal|oblique|italic)/i))&&p[1]&&(q=p[1].substr(0,1).toLowerCase()),(p=h.match(/([1-9]00|normal|bold)/i))&&p[1]&&(/bold/i.test(p[1])?n=7:/[1-9]00/.test(p[1])&&(n=parseInt(p[1].substr(0,1),10))));l.call(k,new t(m,q+n))}a(d.a)},G(this.c,(this.f.api||"https://f.fontdeck.com/s/css/js/")+na(this.c)+"/"+b+".js",function(e){e&&
a([])})):a([])};var v=new ca(window);v.a.c.custom=function(a,b){return new ea(b,a)};v.a.c.fontdeck=function(a,b){return new ja(b,a)};v.a.c.monotype=function(a,b){return new da(b,a)};v.a.c.typekit=function(a,b){return new ia(b,a)};v.a.c.google=function(a,b){return new ha(b,a)};var K={load:u(v.load,v)};"function"===typeof define&&define.amd?define(function(){return K}):"undefined"!==typeof module&&module.exports?module.exports=K:(window.WebFont=K,window.WebFontConfig&&v.load(window.WebFontConfig))})();
